import ActionModal from './modal/ActionModal.component';
import AppBar from './appbar/AppBar.component';
import ButtonC from './button/Button.component';
import ButtonLink from './button/ButtonLink.component';
import ButtonForm from './button/ButtonForm.component';
import ButtonSearch from './button/ButtonSearch.component';
import ButtonImport from './button/ButtonImport.component';
import { ContainerStyled } from './container/Container';
import Drawer from './drawer/Drawer.component';
import { FormInput, FormInputNumber, FormInputMultiline, FormSelect, ContainerRadio, LabelForm, FormRadio, FormControlRadio, DatePicker } from './form/InputStyle';
import HeaderC from './header/Header.component';
import HeaderRegisterC from './header/HeaderRegister.component';
import GridC from "./grid/GridComponent.component";
import { Main, Hearder } from './menu/MenuStyle';
import ModalC from './modal/Modal.component';
import ModalDelete from './modal/ModalDelete.component';
import ProgressC from './progress/Progress.component';
import ToolBar from './toolbar/ToolBar.component';
import TableC from './table/Table.component';
import CardC from './card/Card.component';
import MandatoryFieldSignaling from './mandatoryFieldSignaling/MandatoryFieldSignaling.component';
import Tab from './tabs/Tabs.component';
import CardFormC from './card/CardForm.component';
import { SpanStyled } from './span/SpanStyle';
import ButtonHome from './button/ButtonHome.component';
import MenuPages from './menu/Menu.component';

export const Menu = { Drawer, AppBar, ToolBar, Main, MenuPages, Hearder };
export const Container = ContainerStyled;
export const Form = { FormInput, FormInputNumber, FormInputMultiline, FormSelect, ContainerRadio, LabelForm, FormRadio, FormControlRadio, DatePicker };
export const Header = HeaderC;
export const Progress = ProgressC;
export const Table = TableC;
export const Button = { ButtonC, ButtonLink, ButtonForm, ButtonSearch, ButtonImport, ButtonHome };
export const Modal = { ModalC, ActionModal, ModalDelete };
export const Card = CardC;
export const CardForm = CardFormC;
export const GridComponent = GridC;
export const HeaderRegister = HeaderRegisterC;
export const FieldSignaling = MandatoryFieldSignaling;
export const Tabs = Tab;
export const Span = SpanStyled;